export const FEATURES = {
  CITY: 'CITY',
  ROAD: 'ROAD',
  MONASTERY: 'MONASTERY',
  GARDEN: 'GARDEN',
  FARM: 'FARM',
  MAMADA: 'MAMADA',
  BARN: 'BARN',
  CASTLE: 'CASTLE',
  BUY_OR_SELL_MEEPLE: 'BUY_OR_SELL_MEEPLE',
  BAZAAR: 'BAZAAR',
};
