export const INTERFACE = {
  DATE: '',
  MATCH: 0,
  ROUND: 0,
  TURN: 0,

  VICTOR_POINTS: 0,
  SHINDI_POINTS: 0,
  RENAN_POINTS: 0,

  FAIRY_OWNER: '',

  VICTOR_FAIRY_ROUND: 0,
  VICTOR_FAIRY_FEATURE: 0,

  SHINDI_FAIRY_ROUND: 0,
  SHINDI_FAIRY_FEATURE: 0,

  RENAN_FAIRY_ROUND: 0,
  RENAN_FAIRY_FEATURE: 0,

  VICTOR_POINTS_KING_CITY: 0,
  VICTOR_POINTS_KING_ROAD: 0,

  SHINDI_POINTS_KING_CITY: 0,
  SHINDI_POINTS_KING_ROAD: 0,

  RENAN_POINTS_KING_CITY: 0,
  RENAN_POINTS_KING_ROAD: 0,

  // VICTOR_GHOST: 0,
  // VICTOR_POINTS_GHOST: 0,

  // SHINDI_GHOST: 0,
  // SHINDI_POINTS_GHOST: 0,

  // RENAN_GHOST: 0,
  // RENAN_POINTS_GHOST: 0,

  // VICTOR_PRIEST: 0,
  // VICTOR_POINTS_PRIEST: 0,

  // SHINDI_PRIEST: 0,
  // SHINDI_POINTS_PRIEST: 0,

  // RENAN_PRIEST: 0,
  // RENAN_POINTS_PRIEST: 0,

  KING_CITY: '',
  KING_ROAD: '',
  BIGGEST_CITY: 0,
  BIGGEST_ROAD: 0,

  VICTOR_GOLD: 0,
  VICTOR_GOLD_POINTS: 0,
  SHINDI_GOLD: 0,
  SHINDI_GOLD_POINTS: 0,
  RENAN_GOLD: 0,
  RENAN_GOLD_POINTS: 0,

  VICTOR_BARREL: 0,
  VICTOR_BARREL_POINTS: 0,
  SHINDI_BARREL: 0,
  SHINDI_BARREL_POINTS: 0,
  RENAN_BARREL: 0,
  RENAN_BARREL_POINTS: 0,

  VICTOR_WHEAT: 0,
  VICTOR_WHEAT_POINTS: 0,
  SHINDI_WHEAT: 0,
  SHINDI_WHEAT_POINTS: 0,
  RENAN_WHEAT: 0,
  RENAN_WHEAT_POINTS: 0,

  VICTOR_SILK: 0,
  VICTOR_SILK_POINTS: 0,
  SHINDI_SILK: 0,
  SHINDI_SILK_POINTS: 0,
  RENAN_SILK: 0,
  RENAN_SILK_POINTS: 0,

  VICTOR_CONSTRUCTOR: 0,
  SHINDI_CONSTRUCTOR: 0,
  RENAN_CONSTRUCTOR: 0,

  CITIES: 0,
  ROADS: 0,
};
