import { getInterfaceFile, setInterfaceFile } from '../../utils/match';

import { PLAYERS } from '../../types/player';

class GoldService {
  async addGold(PLAYER) {
    const INTERFACE_FILE = getInterfaceFile();

    if (PLAYER === PLAYERS.VICTOR) {
      INTERFACE_FILE.VICTOR_GOLD += 1;

      if (INTERFACE_FILE.VICTOR_GOLD <= 3)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 1;

      if (INTERFACE_FILE.VICTOR_GOLD >= 4 && INTERFACE_FILE.VICTOR_GOLD <= 6)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 2;

      if (INTERFACE_FILE.VICTOR_GOLD >= 7 && INTERFACE_FILE.VICTOR_GOLD <= 9)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 3;

      if (INTERFACE_FILE.VICTOR_GOLD >= 10)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 4;
    }

    if (PLAYER === PLAYERS.SHINDI) {
      INTERFACE_FILE.SHINDI_GOLD += 1;

      if (INTERFACE_FILE.SHINDI_GOLD <= 3)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 1;

      if (INTERFACE_FILE.SHINDI_GOLD >= 4 && INTERFACE_FILE.SHINDI_GOLD <= 6)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 2;

      if (INTERFACE_FILE.SHINDI_GOLD >= 7 && INTERFACE_FILE.SHINDI_GOLD <= 9)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 3;

      if (INTERFACE_FILE.SHINDI_GOLD >= 10)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 4;
    }

    if (PLAYER === PLAYERS.RENAN) {
      INTERFACE_FILE.RENAN_GOLD += 1;

      if (INTERFACE_FILE.RENAN_GOLD <= 3)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 1;

      if (INTERFACE_FILE.RENAN_GOLD >= 4 && INTERFACE_FILE.RENAN_GOLD <= 6)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 2;

      if (INTERFACE_FILE.RENAN_GOLD >= 7 && INTERFACE_FILE.RENAN_GOLD <= 9)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 3;

      if (INTERFACE_FILE.RENAN_GOLD >= 10)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 4;
    }

    setInterfaceFile(INTERFACE_FILE);
  }

  async removeGold(PLAYER) {
    const INTERFACE_FILE = getInterfaceFile();

    if (PLAYER === PLAYERS.VICTOR) {
      INTERFACE_FILE.VICTOR_GOLD -= 1;

      if (INTERFACE_FILE.VICTOR_GOLD <= 3)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 1;

      if (INTERFACE_FILE.VICTOR_GOLD >= 4 && INTERFACE_FILE.VICTOR_GOLD <= 6)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 2;

      if (INTERFACE_FILE.VICTOR_GOLD >= 7 && INTERFACE_FILE.VICTOR_GOLD <= 9)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 3;

      if (INTERFACE_FILE.VICTOR_GOLD >= 10)
        INTERFACE_FILE.VICTOR_GOLD_POINTS = INTERFACE_FILE.VICTOR_GOLD * 4;
    }

    if (PLAYER === PLAYERS.SHINDI) {
      INTERFACE_FILE.SHINDI_GOLD -= 1;

      if (INTERFACE_FILE.SHINDI_GOLD <= 3)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 1;

      if (INTERFACE_FILE.SHINDI_GOLD >= 4 && INTERFACE_FILE.SHINDI_GOLD <= 6)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 2;

      if (INTERFACE_FILE.SHINDI_GOLD >= 7 && INTERFACE_FILE.SHINDI_GOLD <= 9)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 3;

      if (INTERFACE_FILE.SHINDI_GOLD >= 10)
        INTERFACE_FILE.SHINDI_GOLD_POINTS = INTERFACE_FILE.SHINDI_GOLD * 4;
    }

    if (PLAYER === PLAYERS.RENAN) {
      INTERFACE_FILE.RENAN_GOLD -= 1;

      if (INTERFACE_FILE.RENAN_GOLD <= 3)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 1;

      if (INTERFACE_FILE.RENAN_GOLD >= 4 && INTERFACE_FILE.RENAN_GOLD <= 6)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 2;

      if (INTERFACE_FILE.RENAN_GOLD >= 7 && INTERFACE_FILE.RENAN_GOLD <= 9)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 3;

      if (INTERFACE_FILE.RENAN_GOLD >= 10)
        INTERFACE_FILE.RENAN_GOLD_POINTS = INTERFACE_FILE.RENAN_GOLD * 4;
    }

    setInterfaceFile(INTERFACE_FILE);
  }
}

export default new GoldService();
